/*
 * This file is generated by jOOQ.
 */
package org.jesse.passkey.dbaccess;


import org.jesse.passkey.dbaccess.tables.PasskeyDemo;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>jesse</code> schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PASSKEY_DEMO_IDX_USER_HANDLE = Indexes0.PASSKEY_DEMO_IDX_USER_HANDLE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {

        public static Index PASSKEY_DEMO_IDX_USER_HANDLE = Internal.createIndex("idx_user_handle", PasskeyDemo.PASSKEY_DEMO,
            new OrderField[]{PasskeyDemo.PASSKEY_DEMO.USER_HANDLE}, false);

    }

}
