/*
 * This file is generated by jOOQ.
 */
package org.jesse.passkey.dbaccess;


import java.util.Arrays;
import java.util.List;
import org.jesse.passkey.dbaccess.tables.PasskeyDemo;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Jesse extends SchemaImpl {

    private static final long serialVersionUID = -311744884;

    /**
     * The reference instance of <code>jesse</code>
     */
    public static final Jesse JESSE = new Jesse();

    /**
     * The table <code>jesse.passkey_demo</code>.
     */
    public final PasskeyDemo PASSKEY_DEMO = PasskeyDemo.PASSKEY_DEMO;

    /**
     * No further instances allowed
     */
    private Jesse() {
        super("jesse", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            PasskeyDemo.PASSKEY_DEMO);
    }

}
