/*
 * This file is generated by jOOQ.
 */
package org.jesse.passkey.dbaccess;


import org.jesse.passkey.dbaccess.tables.PasskeyDemo;
import org.jesse.passkey.dbaccess.tables.records.PasskeyDemoRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>jesse</code> schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PasskeyDemoRecord> KEY_PASSKEY_DEMO_PRIMARY = UniqueKeys0.KEY_PASSKEY_DEMO_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {

        public static final UniqueKey<PasskeyDemoRecord> KEY_PASSKEY_DEMO_PRIMARY = Internal.createUniqueKey(PasskeyDemo.PASSKEY_DEMO,
            "KEY_passkey_demo_PRIMARY", new TableField[]{PasskeyDemo.PASSKEY_DEMO.CRED_ID}, true);

    }

}
