/*
 * This file is generated by jOOQ.
 */
package org.jesse.passkey.dbaccess;


import org.jesse.passkey.dbaccess.tables.PasskeyDemo;


/**
 * Convenience access to all tables in jesse
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>jesse.passkey_demo</code>.
     */
    public static final PasskeyDemo PASSKEY_DEMO = PasskeyDemo.PASSKEY_DEMO;

}
