/*
 * This file is generated by jOOQ.
 */
package org.jesse.passkey.dbaccess.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PasskeyDemo implements Serializable {

    private static final long serialVersionUID = 1590815304;

    private String credId;
    private String userHandle;
    private String userName;
    private String pubKey;
    private String credType;
    private String transports;
    private String status;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public PasskeyDemo() {
    }

    public PasskeyDemo(PasskeyDemo value) {
        this.credId = value.credId;
        this.userHandle = value.userHandle;
        this.userName = value.userName;
        this.pubKey = value.pubKey;
        this.credType = value.credType;
        this.transports = value.transports;
        this.status = value.status;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public PasskeyDemo(
        String credId,
        String userHandle,
        String userName,
        String pubKey,
        String credType,
        String transports,
        String status,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.credId = credId;
        this.userHandle = userHandle;
        this.userName = userName;
        this.pubKey = pubKey;
        this.credType = credType;
        this.transports = transports;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public String getCredId() {
        return this.credId;
    }

    public void setCredId(String credId) {
        this.credId = credId;
    }

    public String getUserHandle() {
        return this.userHandle;
    }

    public void setUserHandle(String userHandle) {
        this.userHandle = userHandle;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPubKey() {
        return this.pubKey;
    }

    public void setPubKey(String pubKey) {
        this.pubKey = pubKey;
    }

    public String getCredType() {
        return this.credType;
    }

    public void setCredType(String credType) {
        this.credType = credType;
    }

    public String getTransports() {
        return this.transports;
    }

    public void setTransports(String transports) {
        this.transports = transports;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PasskeyDemo (");

        sb.append(credId);
        sb.append(", ").append(userHandle);
        sb.append(", ").append(userName);
        sb.append(", ").append(pubKey);
        sb.append(", ").append(credType);
        sb.append(", ").append(transports);
        sb.append(", ").append(status);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

}
